channels:
- conda-forge
dependencies:
- python =3.12
- lammps =2024.06.27=*openmpi*
- iprpy-data =2023.07.25
- sphinxdft =3.1
- sphinxdft-data =0.0.1
- pyiron_atomistics =0.8.4
- pyiron-data =0.0.30
- nglview =3.1.2
